const wordListENG = [
  'apple',
  'banana',
  'orange',
  'grape',
  'kiwi',
  'pineapple',
  'strawberry',
  'watermelon',
  'blueberry',
  'mango',
  'peach',
  'lemon',
  'lime',
  'cherry',
  'apricot',
  'papaya',
  'blackberry',
  'raspberry',
  'coconut',
  'fig',
  'plum',
  'pear',
  'avocado',
  'cranberry',
  'melon',
  'nectarine',
  'persimmon',
  'dragonfruit',
  'guava',
  'passionfruit',
  'lychee',
  'tangerine',
  'pomegranate',
  'kiwifruit',
  'date',
  'mulberry',
  'olive',
  'kumquat',
  'quince',
  'grapefruit',
  'cantaloupe',
  'honeydew',
  'boysenberry',
  'elderberry',
  'gooseberry',
  'mangosteen',
  'rhubarb',
  'soursop',
  'starfruit',
  'jackfruit',
  'persimmon',
  'clementine',
  'tamarind',
  'acai',
  'plantain',
  'breadfruit',
  'cherimoya',
  'feijoa',
  'kiwano',
  'longan',
  'mamey',
  'pawpaw',
  'sapodilla',
  'sugar-apple',
  'ugli fruit',
  'yuzu',
  'durian',
  'breadfruit',
  'guanabana',
  'jaboticaba',
  'sapote',
  'santol',
  'sweetsop',
  'tamarillo',
  'yangmei',
  'ackee',
  'bilimbi',
  'miracle fruit',
  'pomelo',
  'saw palmetto',
  'sea grape',
  'achacha',
  'citron',
  'cupuacu',
  'gac',
  'huito',
  'horned melon',
  'pepino',
  'rarefruit',
  'salak',
  'saskatoon',
  'ube',
  'warrior plum',
  'cupuassu',
  'sugarplum',
  'salmonberry',
  'bush tomato',
  'damson plum',
  'rambutan',
  'grumichama',
  'african cucumber',
  'quandong',
  'mombin',
  'native tamarind',
  'lucuma',
  'achacha',
  'alupag',
  'ambarella',
  'bacupari',
  'barbadine',
  'black sapote',
  'blighia',
  'carob',
  'chebulic myrobalan',
  'coromandel gooseberry',
  'cynometra',
  'dabai',
  'green sapote',
  'guaçatonga',
  'guarana',
  'hala fruit',
  'hog plum',
  'indian gooseberry',
  'jambul',
  'kapok',
  'kepel fruit',
  'kundong',
  'lamut',
  'langsat',
  'lemon aspen',
  'longkong',
  'loquat',
  'mabolo',
  'mahogany grape',
  'mango steen',
  'marang',
  'mata kucing',
  'miracle fruit',
  'native rosella',
  'noni',
  'pandan',
  'pulasan',
  'rahang',
  'rattan fruit',
  'roselle',
  'safou',
  'salsify',
  'santol',
  'snake fruit',
  'solanum quitoense',
  'soncoya',
  'souari nut',
  'star apple',
  'strawberry tree',
  'sugar apple',
  'tamarind',
  'tarap',
  'tibetan goji',
  'tucumã',
  'wild peach',
  'wood apple',
  'xylocarp',
  'yantok',
  'yumberry',
  'zapote',
  'ziziphus mauritiana',
  'jabuticaba',
  'olive',
  'papaya',
  'passionfruit',
  'lychee',
  'tangerine',
  'pomegranate',
  'kiwifruit',
  'date',
  'mulberry',
  'olive',
  'kumquat',
  'quince',
  'grapefruit',
  'cantaloupe',
  'honeydew',
  'boysenberry',
  'elderberry',
  'gooseberry',
  'mangosteen',
  'rhubarb',
  'soursop',
  'starfruit',
  'jackfruit',
  'persimmon',
  'clementine',
  'tamarind',
  'acai',
  'plantain',
  'breadfruit',
  'cherimoya',
  'feijoa',
  'kiwano',
  'longan',
  'mamey',
  'pawpaw',
  'sapodilla',
  'sugar-apple',
  'ugli fruit',
  'yuzu',
  'durian',
  'breadfruit',
  'guanabana',
  'jaboticaba',
  'sapote',
  'santol',
  'sweetsop',
  'tamarillo',
  'yangmei',
  'ackee',
  'bilimbi',
  'miracle fruit',
  'pomelo',
  'saw palmetto',
  'sea grape',
  'achacha',
  'citron',
  'cupuacu',
  'gac',
  'huito',
  'horned melon',
  'pepino',
  'rarefruit',
  'salak',
  'saskatoon',
  'ube',
  'warrior plum',
  'cupuassu',
  'sugarplum',
  'salmonberry',
  'bush tomato',
  'damson plum',
  'rambutan',
  'grumichama',
  'african cucumber',
  'quandong',
  'mombin',
  'native tamarind',
  'lucuma',
  'achacha',
  'alupag',
  'ambarella',
  'bacupari',
  'barbadine',
  'black sapote',
  'blighia',
  'carob',
  'chebulic myrobalan',
  'coromandel gooseberry',
  'cynometra',
  'dabai',
  'green sapote',
];

export default wordListENG;
